C ugeant.h
C GEANT で使われる COMMON
C        INTEGER*4 GCBANK_SIZE,SIZE    
        INTEGER*4 GCBANK_SIZE    
        PARAMETER (GCBANK_SIZE=800000)
C        PARAMETER (SIZE=GCBANK_SIZE-24)     
        PARAMETER (KWBANK=6900,KWWORK=5200)     
        PARAMETER (MAXMEC=30)  
        CHARACTER*4 NAMEC   
C  
        COMMON/GCBANK/NZEBRA,GVERSN,ZVERSN,IXSTOR,IXDIV  
     +        ,IXCONS,FENDQ(16),LMAIN,LR1,WS(KWBANK)  
        DIMENSION IQ(2),Q(2),LQ(8000),IWS(2)  
        EQUIVALENCE (Q(1),IQ(1),LQ(9)),(LQ(1),LMAIN),(IWS(1),WS(1))  
        EQUIVALENCE (JCG,JGSTAT)  
C
	COMMON/GCCUTS/CUTGAM,CUTEL,CUTNEU,CUTHAD,CUTMUO,BCUTE,BCUTM
     +        ,DCUTE,DCUTM,PPCUTM,TOFMAX,GCCUTS(5)  
        COMMON/GCLIST/NHSTA,NGET ,NSAVE,NSETS,NPRIN,NGEOM,NVIEW,NPLOT 
     +        ,NSTAT,LHSTA(20),LGET (20),LSAVE(20),LSETS(20),LPRIN(20) 
     +        ,LGEOM(20),LVIEW(20),LPLOT(20),LSTAT(20) 
C 
        COMMON/GCONST/PI,TWOPI ,PIBY2,DEGRAD,RADDEG,CLIGHT,BIG,EMASS 
C  
        COMMON/GCONSX/EMMU,PMASS,AVO   
C  
        COMMON/GCFLAG/IDEBUG,IDEMIN,IDEMAX,ITEST,IDRUN,IDEVT,IEORUN, 
     +                IEOTRI,IEVENT,ISWIT(10),IFINIT(20),NEVENT,NRNDM(2) 
C   
        COMMON/GCUNIT/LIN,LOUT,NUNITS,LUNITS(5) 
C 
        COMMON/GCLINK/JDIGI,JDRAW,JHEAD,JHITS,JKINE,JMATE,JPART,JROTM, 
     +  JRUNG,JSET,JSTAK,JGSTAT,JTMED,JTRACK,JVERTX,JVOLUM,JXYZ, 
     +  JGPAR,JGPAR2,JSKLT  
C 
        COMMON/GCKINE/IKINE,PKINE(10),ITRA,ISTAK,IVERT,IPART,ITRTYP, 
     +        NAPART(5),AMASS,CHARGE,TLIFE,VERT(3),PVERT(4),IPAOLD  
C 
        COMMON/GCSETS/IHSET,IHDET,ISET,IDET,IDTYPE,NVNAME,NUMBV(20) 
C  
        COMMON/GCKING/KCASE,NGKINE,GKIN(5,100),TOFD(100),IFLGK(100)  
C 
        COMMON/GCMATE/NMAT,NAMATE(5),A,Z,DENS,RADL,ABSL 
C
	COMMON/GCMULO/SINMUL(101),COSMUL(101),SQRMUL(101),OMCMOL
     +  ,CHCMOL,EKMIN,EKMAX,NEKBIN,NEK1,EKINV,GEKA,GEKB
     +  ,EKBIN(200),ELOW(200)
C  
        COMMON/GCTRAK/VECT(7),GETOT,GEKIN,VOUT(7),NMEC,LMEC(MAXMEC)
     +  ,NAMEC(MAXMEC),NSTEP ,MAXNST,DESTEP,DESTEL,SAFETY,SLENG 
     +  ,STEP  ,SNEXT ,SFIELD,TOFG  ,GEKRAT,UPWGHT,IGNEXT,INWVOL  
     +  ,ISTOP ,IGAUTO,IEKBIN, ILOSL, IMULL,INGOTO,NLDOWN,NLEVIN  
     +  ,NLVSAV,ISTORY
C
	COMMON/GCTMED/NUMED,NATMED(5),ISVOL,IFIELD,FIELDM,TMAXFD
     +  ,DEEMAX,EPSIL,STMIN,CFIELD,CMULS,IUPD,ISTPAR,NUMOLD
C
	COMMON/GCNUM/NMATE,NVOLUM,NROTM,NTMED,NTMULT,NTRACK,NPART
     +  ,NSTMAX,NVERTX,NHEAD,NBIT
C
	COMMON/GCVOLU/NLEVEL,NAMES(15),NUMBER(15),LVOLUM(15)
     +	,LINDEX(15),INFROM,NLEVMX,NLDEV(15),LINMX(15),GTRAN(3,15)
     +	,GRMAT(10,15),GONLY(15),GLX(3)
C
        COMMON/BAIRITU/ZOOM(2)
